quarterly maintenance for 442 and  6021
oracle-livelabs/converged pull request #118
Opened 2024-11-02 01:37 UTC by paulparkinson

# 442 and  6021 

# General requirements
1. Information in the workshop is adequate and updated
2. Code is correct and working
3. Links are correct
4. Make sure you enter the help email link in your manifest.json
5. Please make sure WMS URLs are updated as needed after your PR is approved

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [ ] All filenames are lower case (including folders, images, files, etc.)
- [ ] Filenames are descriptive
- [ ] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [ ] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [ ] Image references in markdown contain an alternate text

2024-11-04 14:41 UTC, carmenberdant1 requested changes
Hi @paulparkinson, for Workshop 442, could you please replace the Get Started lab with the version for the Brown Button, and insert the Development GitHub link in the Self-QA Checklist in WMS?
Additionally, for Workshop 6021, please update the Acknowledgment section of those md files you updated with the Last Updated date. 
Also for these images please blur the tenancy: 
- microservices-with-converged-db/setup/images/get-oke-info.png 
- microservices-with-converged-db/setup/images/get-oke-details.png
Thank you!

2024-11-06 02:32 UTC, paulparkinson commented
@carmenberdant1 changes made, thanks

2024-11-06 02:36 UTC, paulparkinson commented
I was, however, unable to update the Self-QA Checklist in WMS as it is grayed out - I guess it can not be reactivated until another quarter passes?

2024-11-06 07:31 UTC, carmenberdant1 approved these changes

2024-11-06 07:32 UTC, merged