Update index.html
oracle-livelabs/converged pull request #9
Opened 2022-07-06 02:44 UTC by RichardExley

index.html change as requested

2022-07-06 02:45 UTC, RichardExley commented
workshop #11025

2022-07-07 00:35 UTC, arabellayao requested changes
Hi! Please include the workshop's WMS ID on your PR's title. Thank you!

2022-07-07 18:23 UTC, anooshapilli approved these changes

2022-07-07 23:18 UTC, arabellayao approved these changes

2022-07-07 23:18 UTC, merged